#Creating a Security Group:
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is a Security Group created by CF
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
